# logic:
# a random number would be generated
# while the number is not the same as the number generated by the programm and the user has not typed in exit the programm would go on
# the user would be asked to guss the number
# if the user's guss was higher than the number we would instruct it to aim lower
# if the user was gussing lower than the number we would instruct them to aim higher
# at each stage we would have the user guss agin until one of the two conditions are met
# at each try we woudl incriment the count variable by one so we can keep a record of the number of times that the user has tried to guss the number right
import random
rndm=random.randint(0,100)
print(rndm)
count = 1
guss = ''
while guss!="exit" and guss!=rndm:
    guss = int(input('what do you think the number is? '))
    if guss>rndm:
        if guss-10<=rndm:
            print('high but you are quite close')
            count += 1
        else:
            print('you are eay too hight')
            count += 1
    elif guss<rndm:
        if guss+10>=rndm:
            print('low but you are quite close')
            count += 1
        else:
            print('you are way too low')
            count += 1
if guss == "exit":
    print('thank you for playing')
elif guss==rndm:
    print(f'you gussed right and it only took you {count} times')
else:
    print('what are you looking for? ')
